require:

AllCops:
  NewCops: enable
  Exclude:
    - '_site/**/*'
    - 'vendor/**/*'

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false

# Allow slightly higher metrics for plugin configuration
Metrics/AbcSize:
  Max: 23

Metrics/MethodLength:
  Max: 18
